# .github/workflows/build-exe.yml
name: Build EXE and Create Release

# Controls when the workflow will run
on:
  push:
    branches: [ main ] # Trigger only on pushes to the main branch

permissions:
  contents: write # Needed to create releases and upload assets

jobs:
  build-and-release:
    runs-on: windows-latest # Use a Windows runner for building the .exe

    steps:
      # 1. Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Or your desired Python version

      # 3. Install dependencies
      #    Consider using a requirements.txt file for better management
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Build the executable using PyInstaller
      #    !!! IMPORTANT: Replace 'your_script_name.py' with the actual filename of your Python script !!!
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed `
            --icon=logo.ico `
            --hidden-import tkinter `
            --hidden-import win32timezone `
            --hidden-import win32com `
            --hidden-import win32com.client `
            --add-data "logo.png;." `
            --add-data "logo.ico;." `
            --manifest "win11-readiness.manifest" `
            --name "Win11ReadinessCheck" `
            win11-readiness.py # <<<!!! CHANGE THIS FILENAME !!!>>>

      # 5. Create Release Tag Name
      - name: Create Release Tag Name
        id: tagger
        run: echo "tag_name=release-$(Get-Date -Format 'yyyyMMddHHmmss')" >> $env:GITHUB_OUTPUT
        shell: pwsh # Use PowerShell for date formatting

      # 6. Create GitHub Release and Upload Asset
      #    Uses softprops/action-gh-release which combines creating the release
      #    and uploading assets found via the 'files' pattern.
      - name: Create Release and Upload EXE
        uses: softprops/action-gh-release@v2 # Use v2 or newer
        with:
          tag_name: ${{ steps.tagger.outputs.tag_name }}
          name: "Automated Release ${{ steps.tagger.outputs.tag_name }}"
          body: |
            Automated build of Win11 Readiness Check tool.
            Triggered by commit: ${{ github.sha }}
          files: |
            dist/Win11ReadinessCheck.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the default token
